/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyMethodRouteImport } from './routes/verify-method'
import { Route as SmsVerifyRouteImport } from './routes/sms-verify'
import { Route as SmsPhoneRouteImport } from './routes/sms-phone'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as PasswordRouteImport } from './routes/password'
import { Route as ExpiredRouteImport } from './routes/expired'
import { Route as CompleteSkippedRouteImport } from './routes/complete-skipped'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as AuthenticatorVerifyRouteImport } from './routes/authenticator-verify'
import { Route as AuthenticatorQrRouteImport } from './routes/authenticator-qr'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PatientWelcomeRouteImport } from './routes/patient.welcome'
import { Route as PatientVerifyMethodRouteImport } from './routes/patient.verify-method'
import { Route as PatientSmsVerifyRouteImport } from './routes/patient.sms-verify'
import { Route as PatientSmsPhoneRouteImport } from './routes/patient.sms-phone'
import { Route as PatientPasswordRouteImport } from './routes/patient.password'
import { Route as PatientCompleteSkippedRouteImport } from './routes/patient.complete-skipped'
import { Route as PatientCompleteRouteImport } from './routes/patient.complete'
import { Route as PatientAuthenticatorVerifyRouteImport } from './routes/patient.authenticator-verify'
import { Route as PatientAuthenticatorQrRouteImport } from './routes/patient.authenticator-qr'
import { Route as DashboardPatientIdRouteImport } from './routes/dashboard.$patientId'
import { Route as AdminResourcesRouteImport } from './routes/admin.resources'
import { Route as AdminPlatformRouteImport } from './routes/admin.platform'
import { Route as AdminPatientsRouteImport } from './routes/admin.patients'
import { Route as AdminFormsRouteImport } from './routes/admin.forms'
import { Route as AdminDashboardsRouteImport } from './routes/admin.dashboards'
import { Route as AdminCliniciansRouteImport } from './routes/admin.clinicians'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as DashboardPatientIdIndexRouteImport } from './routes/dashboard.$patientId.index'
import { Route as AdminResourcesIndexRouteImport } from './routes/admin.resources.index'
import { Route as AdminPatientsIndexRouteImport } from './routes/admin.patients.index'
import { Route as AdminFormsIndexRouteImport } from './routes/admin.forms.index'
import { Route as AdminCliniciansIndexRouteImport } from './routes/admin.clinicians.index'
import { Route as DashboardPatientIdProfileRouteImport } from './routes/dashboard.$patientId.profile'
import { Route as AdminResourcesNewRouteImport } from './routes/admin.resources.new'
import { Route as AdminResourcesIdRouteImport } from './routes/admin.resources.$id'
import { Route as AdminPatientsNewRouteImport } from './routes/admin.patients.new'
import { Route as AdminPatientsIdRouteImport } from './routes/admin.patients.$id'
import { Route as AdminFormsNewRouteImport } from './routes/admin.forms.new'
import { Route as AdminFormsIdRouteImport } from './routes/admin.forms.$id'
import { Route as AdminCliniciansNewRouteImport } from './routes/admin.clinicians.new'
import { Route as AdminCliniciansBatchRouteImport } from './routes/admin.clinicians.batch'
import { Route as AdminCliniciansIdRouteImport } from './routes/admin.clinicians.$id'
import { Route as AdminPatientsNewIndexRouteImport } from './routes/admin.patients.new.index'
import { Route as AdminPatientsNewSupportersRouteImport } from './routes/admin.patients.new.supporters'
import { Route as AdminPatientsNewReviewRouteImport } from './routes/admin.patients.new.review'
import { Route as AdminPatientsNewDoneRouteImport } from './routes/admin.patients.new.done'
import { Route as AdminPatientsNewBatchRouteImport } from './routes/admin.patients.new.batch'

const VerifyMethodRoute = VerifyMethodRouteImport.update({
  id: '/verify-method',
  path: '/verify-method',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsVerifyRoute = SmsVerifyRouteImport.update({
  id: '/sms-verify',
  path: '/sms-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsPhoneRoute = SmsPhoneRouteImport.update({
  id: '/sms-phone',
  path: '/sms-phone',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordRoute = PasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpiredRoute = ExpiredRouteImport.update({
  id: '/expired',
  path: '/expired',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteSkippedRoute = CompleteSkippedRouteImport.update({
  id: '/complete-skipped',
  path: '/complete-skipped',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatorVerifyRoute = AuthenticatorVerifyRouteImport.update({
  id: '/authenticator-verify',
  path: '/authenticator-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatorQrRoute = AuthenticatorQrRouteImport.update({
  id: '/authenticator-qr',
  path: '/authenticator-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PatientWelcomeRoute = PatientWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => PatientRoute,
} as any)
const PatientVerifyMethodRoute = PatientVerifyMethodRouteImport.update({
  id: '/verify-method',
  path: '/verify-method',
  getParentRoute: () => PatientRoute,
} as any)
const PatientSmsVerifyRoute = PatientSmsVerifyRouteImport.update({
  id: '/sms-verify',
  path: '/sms-verify',
  getParentRoute: () => PatientRoute,
} as any)
const PatientSmsPhoneRoute = PatientSmsPhoneRouteImport.update({
  id: '/sms-phone',
  path: '/sms-phone',
  getParentRoute: () => PatientRoute,
} as any)
const PatientPasswordRoute = PatientPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => PatientRoute,
} as any)
const PatientCompleteSkippedRoute = PatientCompleteSkippedRouteImport.update({
  id: '/complete-skipped',
  path: '/complete-skipped',
  getParentRoute: () => PatientRoute,
} as any)
const PatientCompleteRoute = PatientCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAuthenticatorVerifyRoute =
  PatientAuthenticatorVerifyRouteImport.update({
    id: '/authenticator-verify',
    path: '/authenticator-verify',
    getParentRoute: () => PatientRoute,
  } as any)
const PatientAuthenticatorQrRoute = PatientAuthenticatorQrRouteImport.update({
  id: '/authenticator-qr',
  path: '/authenticator-qr',
  getParentRoute: () => PatientRoute,
} as any)
const DashboardPatientIdRoute = DashboardPatientIdRouteImport.update({
  id: '/dashboard/$patientId',
  path: '/dashboard/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResourcesRoute = AdminResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlatformRoute = AdminPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormsRoute = AdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardsRoute = AdminDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCliniciansRoute = AdminCliniciansRouteImport.update({
  id: '/clinicians',
  path: '/clinicians',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardPatientIdIndexRoute = DashboardPatientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardPatientIdRoute,
} as any)
const AdminResourcesIndexRoute = AdminResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminResourcesRoute,
} as any)
const AdminPatientsIndexRoute = AdminPatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPatientsRoute,
} as any)
const AdminFormsIndexRoute = AdminFormsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminFormsRoute,
} as any)
const AdminCliniciansIndexRoute = AdminCliniciansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCliniciansRoute,
} as any)
const DashboardPatientIdProfileRoute =
  DashboardPatientIdProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardPatientIdRoute,
  } as any)
const AdminResourcesNewRoute = AdminResourcesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminResourcesRoute,
} as any)
const AdminResourcesIdRoute = AdminResourcesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminResourcesRoute,
} as any)
const AdminPatientsNewRoute = AdminPatientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPatientsRoute,
} as any)
const AdminPatientsIdRoute = AdminPatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPatientsRoute,
} as any)
const AdminFormsNewRoute = AdminFormsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminFormsRoute,
} as any)
const AdminFormsIdRoute = AdminFormsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminFormsRoute,
} as any)
const AdminCliniciansNewRoute = AdminCliniciansNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminCliniciansRoute,
} as any)
const AdminCliniciansBatchRoute = AdminCliniciansBatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => AdminCliniciansRoute,
} as any)
const AdminCliniciansIdRoute = AdminCliniciansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCliniciansRoute,
} as any)
const AdminPatientsNewIndexRoute = AdminPatientsNewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPatientsNewRoute,
} as any)
const AdminPatientsNewSupportersRoute =
  AdminPatientsNewSupportersRouteImport.update({
    id: '/supporters',
    path: '/supporters',
    getParentRoute: () => AdminPatientsNewRoute,
  } as any)
const AdminPatientsNewReviewRoute = AdminPatientsNewReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AdminPatientsNewRoute,
} as any)
const AdminPatientsNewDoneRoute = AdminPatientsNewDoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => AdminPatientsNewRoute,
} as any)
const AdminPatientsNewBatchRoute = AdminPatientsNewBatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => AdminPatientsNewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/authenticator-qr': typeof AuthenticatorQrRoute
  '/authenticator-verify': typeof AuthenticatorVerifyRoute
  '/complete': typeof CompleteRoute
  '/complete-skipped': typeof CompleteSkippedRoute
  '/expired': typeof ExpiredRoute
  '/password': typeof PasswordRoute
  '/patient': typeof PatientRouteWithChildren
  '/roster': typeof RosterRoute
  '/sms-phone': typeof SmsPhoneRoute
  '/sms-verify': typeof SmsVerifyRoute
  '/verify-method': typeof VerifyMethodRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/clinicians': typeof AdminCliniciansRouteWithChildren
  '/admin/dashboards': typeof AdminDashboardsRoute
  '/admin/forms': typeof AdminFormsRouteWithChildren
  '/admin/patients': typeof AdminPatientsRouteWithChildren
  '/admin/platform': typeof AdminPlatformRoute
  '/admin/resources': typeof AdminResourcesRouteWithChildren
  '/dashboard/$patientId': typeof DashboardPatientIdRouteWithChildren
  '/patient/authenticator-qr': typeof PatientAuthenticatorQrRoute
  '/patient/authenticator-verify': typeof PatientAuthenticatorVerifyRoute
  '/patient/complete': typeof PatientCompleteRoute
  '/patient/complete-skipped': typeof PatientCompleteSkippedRoute
  '/patient/password': typeof PatientPasswordRoute
  '/patient/sms-phone': typeof PatientSmsPhoneRoute
  '/patient/sms-verify': typeof PatientSmsVerifyRoute
  '/patient/verify-method': typeof PatientVerifyMethodRoute
  '/patient/welcome': typeof PatientWelcomeRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/clinicians/$id': typeof AdminCliniciansIdRoute
  '/admin/clinicians/batch': typeof AdminCliniciansBatchRoute
  '/admin/clinicians/new': typeof AdminCliniciansNewRoute
  '/admin/forms/$id': typeof AdminFormsIdRoute
  '/admin/forms/new': typeof AdminFormsNewRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/admin/patients/new': typeof AdminPatientsNewRouteWithChildren
  '/admin/resources/$id': typeof AdminResourcesIdRoute
  '/admin/resources/new': typeof AdminResourcesNewRoute
  '/dashboard/$patientId/profile': typeof DashboardPatientIdProfileRoute
  '/admin/clinicians/': typeof AdminCliniciansIndexRoute
  '/admin/forms/': typeof AdminFormsIndexRoute
  '/admin/patients/': typeof AdminPatientsIndexRoute
  '/admin/resources/': typeof AdminResourcesIndexRoute
  '/dashboard/$patientId/': typeof DashboardPatientIdIndexRoute
  '/admin/patients/new/batch': typeof AdminPatientsNewBatchRoute
  '/admin/patients/new/done': typeof AdminPatientsNewDoneRoute
  '/admin/patients/new/review': typeof AdminPatientsNewReviewRoute
  '/admin/patients/new/supporters': typeof AdminPatientsNewSupportersRoute
  '/admin/patients/new/': typeof AdminPatientsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authenticator-qr': typeof AuthenticatorQrRoute
  '/authenticator-verify': typeof AuthenticatorVerifyRoute
  '/complete': typeof CompleteRoute
  '/complete-skipped': typeof CompleteSkippedRoute
  '/expired': typeof ExpiredRoute
  '/password': typeof PasswordRoute
  '/patient': typeof PatientRouteWithChildren
  '/roster': typeof RosterRoute
  '/sms-phone': typeof SmsPhoneRoute
  '/sms-verify': typeof SmsVerifyRoute
  '/verify-method': typeof VerifyMethodRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboards': typeof AdminDashboardsRoute
  '/admin/platform': typeof AdminPlatformRoute
  '/patient/authenticator-qr': typeof PatientAuthenticatorQrRoute
  '/patient/authenticator-verify': typeof PatientAuthenticatorVerifyRoute
  '/patient/complete': typeof PatientCompleteRoute
  '/patient/complete-skipped': typeof PatientCompleteSkippedRoute
  '/patient/password': typeof PatientPasswordRoute
  '/patient/sms-phone': typeof PatientSmsPhoneRoute
  '/patient/sms-verify': typeof PatientSmsVerifyRoute
  '/patient/verify-method': typeof PatientVerifyMethodRoute
  '/patient/welcome': typeof PatientWelcomeRoute
  '/admin': typeof AdminIndexRoute
  '/admin/clinicians/$id': typeof AdminCliniciansIdRoute
  '/admin/clinicians/batch': typeof AdminCliniciansBatchRoute
  '/admin/clinicians/new': typeof AdminCliniciansNewRoute
  '/admin/forms/$id': typeof AdminFormsIdRoute
  '/admin/forms/new': typeof AdminFormsNewRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/admin/resources/$id': typeof AdminResourcesIdRoute
  '/admin/resources/new': typeof AdminResourcesNewRoute
  '/dashboard/$patientId/profile': typeof DashboardPatientIdProfileRoute
  '/admin/clinicians': typeof AdminCliniciansIndexRoute
  '/admin/forms': typeof AdminFormsIndexRoute
  '/admin/patients': typeof AdminPatientsIndexRoute
  '/admin/resources': typeof AdminResourcesIndexRoute
  '/dashboard/$patientId': typeof DashboardPatientIdIndexRoute
  '/admin/patients/new/batch': typeof AdminPatientsNewBatchRoute
  '/admin/patients/new/done': typeof AdminPatientsNewDoneRoute
  '/admin/patients/new/review': typeof AdminPatientsNewReviewRoute
  '/admin/patients/new/supporters': typeof AdminPatientsNewSupportersRoute
  '/admin/patients/new': typeof AdminPatientsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/authenticator-qr': typeof AuthenticatorQrRoute
  '/authenticator-verify': typeof AuthenticatorVerifyRoute
  '/complete': typeof CompleteRoute
  '/complete-skipped': typeof CompleteSkippedRoute
  '/expired': typeof ExpiredRoute
  '/password': typeof PasswordRoute
  '/patient': typeof PatientRouteWithChildren
  '/roster': typeof RosterRoute
  '/sms-phone': typeof SmsPhoneRoute
  '/sms-verify': typeof SmsVerifyRoute
  '/verify-method': typeof VerifyMethodRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/clinicians': typeof AdminCliniciansRouteWithChildren
  '/admin/dashboards': typeof AdminDashboardsRoute
  '/admin/forms': typeof AdminFormsRouteWithChildren
  '/admin/patients': typeof AdminPatientsRouteWithChildren
  '/admin/platform': typeof AdminPlatformRoute
  '/admin/resources': typeof AdminResourcesRouteWithChildren
  '/dashboard/$patientId': typeof DashboardPatientIdRouteWithChildren
  '/patient/authenticator-qr': typeof PatientAuthenticatorQrRoute
  '/patient/authenticator-verify': typeof PatientAuthenticatorVerifyRoute
  '/patient/complete': typeof PatientCompleteRoute
  '/patient/complete-skipped': typeof PatientCompleteSkippedRoute
  '/patient/password': typeof PatientPasswordRoute
  '/patient/sms-phone': typeof PatientSmsPhoneRoute
  '/patient/sms-verify': typeof PatientSmsVerifyRoute
  '/patient/verify-method': typeof PatientVerifyMethodRoute
  '/patient/welcome': typeof PatientWelcomeRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/clinicians/$id': typeof AdminCliniciansIdRoute
  '/admin/clinicians/batch': typeof AdminCliniciansBatchRoute
  '/admin/clinicians/new': typeof AdminCliniciansNewRoute
  '/admin/forms/$id': typeof AdminFormsIdRoute
  '/admin/forms/new': typeof AdminFormsNewRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/admin/patients/new': typeof AdminPatientsNewRouteWithChildren
  '/admin/resources/$id': typeof AdminResourcesIdRoute
  '/admin/resources/new': typeof AdminResourcesNewRoute
  '/dashboard/$patientId/profile': typeof DashboardPatientIdProfileRoute
  '/admin/clinicians/': typeof AdminCliniciansIndexRoute
  '/admin/forms/': typeof AdminFormsIndexRoute
  '/admin/patients/': typeof AdminPatientsIndexRoute
  '/admin/resources/': typeof AdminResourcesIndexRoute
  '/dashboard/$patientId/': typeof DashboardPatientIdIndexRoute
  '/admin/patients/new/batch': typeof AdminPatientsNewBatchRoute
  '/admin/patients/new/done': typeof AdminPatientsNewDoneRoute
  '/admin/patients/new/review': typeof AdminPatientsNewReviewRoute
  '/admin/patients/new/supporters': typeof AdminPatientsNewSupportersRoute
  '/admin/patients/new/': typeof AdminPatientsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/authenticator-qr'
    | '/authenticator-verify'
    | '/complete'
    | '/complete-skipped'
    | '/expired'
    | '/password'
    | '/patient'
    | '/roster'
    | '/sms-phone'
    | '/sms-verify'
    | '/verify-method'
    | '/admin/audit'
    | '/admin/clinicians'
    | '/admin/dashboards'
    | '/admin/forms'
    | '/admin/patients'
    | '/admin/platform'
    | '/admin/resources'
    | '/dashboard/$patientId'
    | '/patient/authenticator-qr'
    | '/patient/authenticator-verify'
    | '/patient/complete'
    | '/patient/complete-skipped'
    | '/patient/password'
    | '/patient/sms-phone'
    | '/patient/sms-verify'
    | '/patient/verify-method'
    | '/patient/welcome'
    | '/admin/'
    | '/admin/clinicians/$id'
    | '/admin/clinicians/batch'
    | '/admin/clinicians/new'
    | '/admin/forms/$id'
    | '/admin/forms/new'
    | '/admin/patients/$id'
    | '/admin/patients/new'
    | '/admin/resources/$id'
    | '/admin/resources/new'
    | '/dashboard/$patientId/profile'
    | '/admin/clinicians/'
    | '/admin/forms/'
    | '/admin/patients/'
    | '/admin/resources/'
    | '/dashboard/$patientId/'
    | '/admin/patients/new/batch'
    | '/admin/patients/new/done'
    | '/admin/patients/new/review'
    | '/admin/patients/new/supporters'
    | '/admin/patients/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authenticator-qr'
    | '/authenticator-verify'
    | '/complete'
    | '/complete-skipped'
    | '/expired'
    | '/password'
    | '/patient'
    | '/roster'
    | '/sms-phone'
    | '/sms-verify'
    | '/verify-method'
    | '/admin/audit'
    | '/admin/dashboards'
    | '/admin/platform'
    | '/patient/authenticator-qr'
    | '/patient/authenticator-verify'
    | '/patient/complete'
    | '/patient/complete-skipped'
    | '/patient/password'
    | '/patient/sms-phone'
    | '/patient/sms-verify'
    | '/patient/verify-method'
    | '/patient/welcome'
    | '/admin'
    | '/admin/clinicians/$id'
    | '/admin/clinicians/batch'
    | '/admin/clinicians/new'
    | '/admin/forms/$id'
    | '/admin/forms/new'
    | '/admin/patients/$id'
    | '/admin/resources/$id'
    | '/admin/resources/new'
    | '/dashboard/$patientId/profile'
    | '/admin/clinicians'
    | '/admin/forms'
    | '/admin/patients'
    | '/admin/resources'
    | '/dashboard/$patientId'
    | '/admin/patients/new/batch'
    | '/admin/patients/new/done'
    | '/admin/patients/new/review'
    | '/admin/patients/new/supporters'
    | '/admin/patients/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/authenticator-qr'
    | '/authenticator-verify'
    | '/complete'
    | '/complete-skipped'
    | '/expired'
    | '/password'
    | '/patient'
    | '/roster'
    | '/sms-phone'
    | '/sms-verify'
    | '/verify-method'
    | '/admin/audit'
    | '/admin/clinicians'
    | '/admin/dashboards'
    | '/admin/forms'
    | '/admin/patients'
    | '/admin/platform'
    | '/admin/resources'
    | '/dashboard/$patientId'
    | '/patient/authenticator-qr'
    | '/patient/authenticator-verify'
    | '/patient/complete'
    | '/patient/complete-skipped'
    | '/patient/password'
    | '/patient/sms-phone'
    | '/patient/sms-verify'
    | '/patient/verify-method'
    | '/patient/welcome'
    | '/admin/'
    | '/admin/clinicians/$id'
    | '/admin/clinicians/batch'
    | '/admin/clinicians/new'
    | '/admin/forms/$id'
    | '/admin/forms/new'
    | '/admin/patients/$id'
    | '/admin/patients/new'
    | '/admin/resources/$id'
    | '/admin/resources/new'
    | '/dashboard/$patientId/profile'
    | '/admin/clinicians/'
    | '/admin/forms/'
    | '/admin/patients/'
    | '/admin/resources/'
    | '/dashboard/$patientId/'
    | '/admin/patients/new/batch'
    | '/admin/patients/new/done'
    | '/admin/patients/new/review'
    | '/admin/patients/new/supporters'
    | '/admin/patients/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatorQrRoute: typeof AuthenticatorQrRoute
  AuthenticatorVerifyRoute: typeof AuthenticatorVerifyRoute
  CompleteRoute: typeof CompleteRoute
  CompleteSkippedRoute: typeof CompleteSkippedRoute
  ExpiredRoute: typeof ExpiredRoute
  PasswordRoute: typeof PasswordRoute
  PatientRoute: typeof PatientRouteWithChildren
  RosterRoute: typeof RosterRoute
  SmsPhoneRoute: typeof SmsPhoneRoute
  SmsVerifyRoute: typeof SmsVerifyRoute
  VerifyMethodRoute: typeof VerifyMethodRoute
  DashboardPatientIdRoute: typeof DashboardPatientIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-method': {
      id: '/verify-method'
      path: '/verify-method'
      fullPath: '/verify-method'
      preLoaderRoute: typeof VerifyMethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms-verify': {
      id: '/sms-verify'
      path: '/sms-verify'
      fullPath: '/sms-verify'
      preLoaderRoute: typeof SmsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms-phone': {
      id: '/sms-phone'
      path: '/sms-phone'
      fullPath: '/sms-phone'
      preLoaderRoute: typeof SmsPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password': {
      id: '/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof PasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expired': {
      id: '/expired'
      path: '/expired'
      fullPath: '/expired'
      preLoaderRoute: typeof ExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-skipped': {
      id: '/complete-skipped'
      path: '/complete-skipped'
      fullPath: '/complete-skipped'
      preLoaderRoute: typeof CompleteSkippedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticator-verify': {
      id: '/authenticator-verify'
      path: '/authenticator-verify'
      fullPath: '/authenticator-verify'
      preLoaderRoute: typeof AuthenticatorVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticator-qr': {
      id: '/authenticator-qr'
      path: '/authenticator-qr'
      fullPath: '/authenticator-qr'
      preLoaderRoute: typeof AuthenticatorQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/patient/welcome': {
      id: '/patient/welcome'
      path: '/welcome'
      fullPath: '/patient/welcome'
      preLoaderRoute: typeof PatientWelcomeRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/verify-method': {
      id: '/patient/verify-method'
      path: '/verify-method'
      fullPath: '/patient/verify-method'
      preLoaderRoute: typeof PatientVerifyMethodRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/sms-verify': {
      id: '/patient/sms-verify'
      path: '/sms-verify'
      fullPath: '/patient/sms-verify'
      preLoaderRoute: typeof PatientSmsVerifyRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/sms-phone': {
      id: '/patient/sms-phone'
      path: '/sms-phone'
      fullPath: '/patient/sms-phone'
      preLoaderRoute: typeof PatientSmsPhoneRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/password': {
      id: '/patient/password'
      path: '/password'
      fullPath: '/patient/password'
      preLoaderRoute: typeof PatientPasswordRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/complete-skipped': {
      id: '/patient/complete-skipped'
      path: '/complete-skipped'
      fullPath: '/patient/complete-skipped'
      preLoaderRoute: typeof PatientCompleteSkippedRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/complete': {
      id: '/patient/complete'
      path: '/complete'
      fullPath: '/patient/complete'
      preLoaderRoute: typeof PatientCompleteRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/authenticator-verify': {
      id: '/patient/authenticator-verify'
      path: '/authenticator-verify'
      fullPath: '/patient/authenticator-verify'
      preLoaderRoute: typeof PatientAuthenticatorVerifyRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/authenticator-qr': {
      id: '/patient/authenticator-qr'
      path: '/authenticator-qr'
      fullPath: '/patient/authenticator-qr'
      preLoaderRoute: typeof PatientAuthenticatorQrRouteImport
      parentRoute: typeof PatientRoute
    }
    '/dashboard/$patientId': {
      id: '/dashboard/$patientId'
      path: '/dashboard/$patientId'
      fullPath: '/dashboard/$patientId'
      preLoaderRoute: typeof DashboardPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/resources': {
      id: '/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AdminResourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/platform': {
      id: '/admin/platform'
      path: '/platform'
      fullPath: '/admin/platform'
      preLoaderRoute: typeof AdminPlatformRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forms': {
      id: '/admin/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboards': {
      id: '/admin/dashboards'
      path: '/dashboards'
      fullPath: '/admin/dashboards'
      preLoaderRoute: typeof AdminDashboardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clinicians': {
      id: '/admin/clinicians'
      path: '/clinicians'
      fullPath: '/admin/clinicians'
      preLoaderRoute: typeof AdminCliniciansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/$patientId/': {
      id: '/dashboard/$patientId/'
      path: '/'
      fullPath: '/dashboard/$patientId/'
      preLoaderRoute: typeof DashboardPatientIdIndexRouteImport
      parentRoute: typeof DashboardPatientIdRoute
    }
    '/admin/resources/': {
      id: '/admin/resources/'
      path: '/'
      fullPath: '/admin/resources/'
      preLoaderRoute: typeof AdminResourcesIndexRouteImport
      parentRoute: typeof AdminResourcesRoute
    }
    '/admin/patients/': {
      id: '/admin/patients/'
      path: '/'
      fullPath: '/admin/patients/'
      preLoaderRoute: typeof AdminPatientsIndexRouteImport
      parentRoute: typeof AdminPatientsRoute
    }
    '/admin/forms/': {
      id: '/admin/forms/'
      path: '/'
      fullPath: '/admin/forms/'
      preLoaderRoute: typeof AdminFormsIndexRouteImport
      parentRoute: typeof AdminFormsRoute
    }
    '/admin/clinicians/': {
      id: '/admin/clinicians/'
      path: '/'
      fullPath: '/admin/clinicians/'
      preLoaderRoute: typeof AdminCliniciansIndexRouteImport
      parentRoute: typeof AdminCliniciansRoute
    }
    '/dashboard/$patientId/profile': {
      id: '/dashboard/$patientId/profile'
      path: '/profile'
      fullPath: '/dashboard/$patientId/profile'
      preLoaderRoute: typeof DashboardPatientIdProfileRouteImport
      parentRoute: typeof DashboardPatientIdRoute
    }
    '/admin/resources/new': {
      id: '/admin/resources/new'
      path: '/new'
      fullPath: '/admin/resources/new'
      preLoaderRoute: typeof AdminResourcesNewRouteImport
      parentRoute: typeof AdminResourcesRoute
    }
    '/admin/resources/$id': {
      id: '/admin/resources/$id'
      path: '/$id'
      fullPath: '/admin/resources/$id'
      preLoaderRoute: typeof AdminResourcesIdRouteImport
      parentRoute: typeof AdminResourcesRoute
    }
    '/admin/patients/new': {
      id: '/admin/patients/new'
      path: '/new'
      fullPath: '/admin/patients/new'
      preLoaderRoute: typeof AdminPatientsNewRouteImport
      parentRoute: typeof AdminPatientsRoute
    }
    '/admin/patients/$id': {
      id: '/admin/patients/$id'
      path: '/$id'
      fullPath: '/admin/patients/$id'
      preLoaderRoute: typeof AdminPatientsIdRouteImport
      parentRoute: typeof AdminPatientsRoute
    }
    '/admin/forms/new': {
      id: '/admin/forms/new'
      path: '/new'
      fullPath: '/admin/forms/new'
      preLoaderRoute: typeof AdminFormsNewRouteImport
      parentRoute: typeof AdminFormsRoute
    }
    '/admin/forms/$id': {
      id: '/admin/forms/$id'
      path: '/$id'
      fullPath: '/admin/forms/$id'
      preLoaderRoute: typeof AdminFormsIdRouteImport
      parentRoute: typeof AdminFormsRoute
    }
    '/admin/clinicians/new': {
      id: '/admin/clinicians/new'
      path: '/new'
      fullPath: '/admin/clinicians/new'
      preLoaderRoute: typeof AdminCliniciansNewRouteImport
      parentRoute: typeof AdminCliniciansRoute
    }
    '/admin/clinicians/batch': {
      id: '/admin/clinicians/batch'
      path: '/batch'
      fullPath: '/admin/clinicians/batch'
      preLoaderRoute: typeof AdminCliniciansBatchRouteImport
      parentRoute: typeof AdminCliniciansRoute
    }
    '/admin/clinicians/$id': {
      id: '/admin/clinicians/$id'
      path: '/$id'
      fullPath: '/admin/clinicians/$id'
      preLoaderRoute: typeof AdminCliniciansIdRouteImport
      parentRoute: typeof AdminCliniciansRoute
    }
    '/admin/patients/new/': {
      id: '/admin/patients/new/'
      path: '/'
      fullPath: '/admin/patients/new/'
      preLoaderRoute: typeof AdminPatientsNewIndexRouteImport
      parentRoute: typeof AdminPatientsNewRoute
    }
    '/admin/patients/new/supporters': {
      id: '/admin/patients/new/supporters'
      path: '/supporters'
      fullPath: '/admin/patients/new/supporters'
      preLoaderRoute: typeof AdminPatientsNewSupportersRouteImport
      parentRoute: typeof AdminPatientsNewRoute
    }
    '/admin/patients/new/review': {
      id: '/admin/patients/new/review'
      path: '/review'
      fullPath: '/admin/patients/new/review'
      preLoaderRoute: typeof AdminPatientsNewReviewRouteImport
      parentRoute: typeof AdminPatientsNewRoute
    }
    '/admin/patients/new/done': {
      id: '/admin/patients/new/done'
      path: '/done'
      fullPath: '/admin/patients/new/done'
      preLoaderRoute: typeof AdminPatientsNewDoneRouteImport
      parentRoute: typeof AdminPatientsNewRoute
    }
    '/admin/patients/new/batch': {
      id: '/admin/patients/new/batch'
      path: '/batch'
      fullPath: '/admin/patients/new/batch'
      preLoaderRoute: typeof AdminPatientsNewBatchRouteImport
      parentRoute: typeof AdminPatientsNewRoute
    }
  }
}

interface AdminCliniciansRouteChildren {
  AdminCliniciansIdRoute: typeof AdminCliniciansIdRoute
  AdminCliniciansBatchRoute: typeof AdminCliniciansBatchRoute
  AdminCliniciansNewRoute: typeof AdminCliniciansNewRoute
  AdminCliniciansIndexRoute: typeof AdminCliniciansIndexRoute
}

const AdminCliniciansRouteChildren: AdminCliniciansRouteChildren = {
  AdminCliniciansIdRoute: AdminCliniciansIdRoute,
  AdminCliniciansBatchRoute: AdminCliniciansBatchRoute,
  AdminCliniciansNewRoute: AdminCliniciansNewRoute,
  AdminCliniciansIndexRoute: AdminCliniciansIndexRoute,
}

const AdminCliniciansRouteWithChildren = AdminCliniciansRoute._addFileChildren(
  AdminCliniciansRouteChildren,
)

interface AdminFormsRouteChildren {
  AdminFormsIdRoute: typeof AdminFormsIdRoute
  AdminFormsNewRoute: typeof AdminFormsNewRoute
  AdminFormsIndexRoute: typeof AdminFormsIndexRoute
}

const AdminFormsRouteChildren: AdminFormsRouteChildren = {
  AdminFormsIdRoute: AdminFormsIdRoute,
  AdminFormsNewRoute: AdminFormsNewRoute,
  AdminFormsIndexRoute: AdminFormsIndexRoute,
}

const AdminFormsRouteWithChildren = AdminFormsRoute._addFileChildren(
  AdminFormsRouteChildren,
)

interface AdminPatientsNewRouteChildren {
  AdminPatientsNewBatchRoute: typeof AdminPatientsNewBatchRoute
  AdminPatientsNewDoneRoute: typeof AdminPatientsNewDoneRoute
  AdminPatientsNewReviewRoute: typeof AdminPatientsNewReviewRoute
  AdminPatientsNewSupportersRoute: typeof AdminPatientsNewSupportersRoute
  AdminPatientsNewIndexRoute: typeof AdminPatientsNewIndexRoute
}

const AdminPatientsNewRouteChildren: AdminPatientsNewRouteChildren = {
  AdminPatientsNewBatchRoute: AdminPatientsNewBatchRoute,
  AdminPatientsNewDoneRoute: AdminPatientsNewDoneRoute,
  AdminPatientsNewReviewRoute: AdminPatientsNewReviewRoute,
  AdminPatientsNewSupportersRoute: AdminPatientsNewSupportersRoute,
  AdminPatientsNewIndexRoute: AdminPatientsNewIndexRoute,
}

const AdminPatientsNewRouteWithChildren =
  AdminPatientsNewRoute._addFileChildren(AdminPatientsNewRouteChildren)

interface AdminPatientsRouteChildren {
  AdminPatientsIdRoute: typeof AdminPatientsIdRoute
  AdminPatientsNewRoute: typeof AdminPatientsNewRouteWithChildren
  AdminPatientsIndexRoute: typeof AdminPatientsIndexRoute
}

const AdminPatientsRouteChildren: AdminPatientsRouteChildren = {
  AdminPatientsIdRoute: AdminPatientsIdRoute,
  AdminPatientsNewRoute: AdminPatientsNewRouteWithChildren,
  AdminPatientsIndexRoute: AdminPatientsIndexRoute,
}

const AdminPatientsRouteWithChildren = AdminPatientsRoute._addFileChildren(
  AdminPatientsRouteChildren,
)

interface AdminResourcesRouteChildren {
  AdminResourcesIdRoute: typeof AdminResourcesIdRoute
  AdminResourcesNewRoute: typeof AdminResourcesNewRoute
  AdminResourcesIndexRoute: typeof AdminResourcesIndexRoute
}

const AdminResourcesRouteChildren: AdminResourcesRouteChildren = {
  AdminResourcesIdRoute: AdminResourcesIdRoute,
  AdminResourcesNewRoute: AdminResourcesNewRoute,
  AdminResourcesIndexRoute: AdminResourcesIndexRoute,
}

const AdminResourcesRouteWithChildren = AdminResourcesRoute._addFileChildren(
  AdminResourcesRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCliniciansRoute: typeof AdminCliniciansRouteWithChildren
  AdminDashboardsRoute: typeof AdminDashboardsRoute
  AdminFormsRoute: typeof AdminFormsRouteWithChildren
  AdminPatientsRoute: typeof AdminPatientsRouteWithChildren
  AdminPlatformRoute: typeof AdminPlatformRoute
  AdminResourcesRoute: typeof AdminResourcesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminCliniciansRoute: AdminCliniciansRouteWithChildren,
  AdminDashboardsRoute: AdminDashboardsRoute,
  AdminFormsRoute: AdminFormsRouteWithChildren,
  AdminPatientsRoute: AdminPatientsRouteWithChildren,
  AdminPlatformRoute: AdminPlatformRoute,
  AdminResourcesRoute: AdminResourcesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PatientRouteChildren {
  PatientAuthenticatorQrRoute: typeof PatientAuthenticatorQrRoute
  PatientAuthenticatorVerifyRoute: typeof PatientAuthenticatorVerifyRoute
  PatientCompleteRoute: typeof PatientCompleteRoute
  PatientCompleteSkippedRoute: typeof PatientCompleteSkippedRoute
  PatientPasswordRoute: typeof PatientPasswordRoute
  PatientSmsPhoneRoute: typeof PatientSmsPhoneRoute
  PatientSmsVerifyRoute: typeof PatientSmsVerifyRoute
  PatientVerifyMethodRoute: typeof PatientVerifyMethodRoute
  PatientWelcomeRoute: typeof PatientWelcomeRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAuthenticatorQrRoute: PatientAuthenticatorQrRoute,
  PatientAuthenticatorVerifyRoute: PatientAuthenticatorVerifyRoute,
  PatientCompleteRoute: PatientCompleteRoute,
  PatientCompleteSkippedRoute: PatientCompleteSkippedRoute,
  PatientPasswordRoute: PatientPasswordRoute,
  PatientSmsPhoneRoute: PatientSmsPhoneRoute,
  PatientSmsVerifyRoute: PatientSmsVerifyRoute,
  PatientVerifyMethodRoute: PatientVerifyMethodRoute,
  PatientWelcomeRoute: PatientWelcomeRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

interface DashboardPatientIdRouteChildren {
  DashboardPatientIdProfileRoute: typeof DashboardPatientIdProfileRoute
  DashboardPatientIdIndexRoute: typeof DashboardPatientIdIndexRoute
}

const DashboardPatientIdRouteChildren: DashboardPatientIdRouteChildren = {
  DashboardPatientIdProfileRoute: DashboardPatientIdProfileRoute,
  DashboardPatientIdIndexRoute: DashboardPatientIdIndexRoute,
}

const DashboardPatientIdRouteWithChildren =
  DashboardPatientIdRoute._addFileChildren(DashboardPatientIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatorQrRoute: AuthenticatorQrRoute,
  AuthenticatorVerifyRoute: AuthenticatorVerifyRoute,
  CompleteRoute: CompleteRoute,
  CompleteSkippedRoute: CompleteSkippedRoute,
  ExpiredRoute: ExpiredRoute,
  PasswordRoute: PasswordRoute,
  PatientRoute: PatientRouteWithChildren,
  RosterRoute: RosterRoute,
  SmsPhoneRoute: SmsPhoneRoute,
  SmsVerifyRoute: SmsVerifyRoute,
  VerifyMethodRoute: VerifyMethodRoute,
  DashboardPatientIdRoute: DashboardPatientIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
