/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyMethodRouteImport } from './routes/verify-method'
import { Route as SmsVerifyRouteImport } from './routes/sms-verify'
import { Route as SmsPhoneRouteImport } from './routes/sms-phone'
import { Route as PasswordRouteImport } from './routes/password'
import { Route as ExpiredRouteImport } from './routes/expired'
import { Route as CompleteSkippedRouteImport } from './routes/complete-skipped'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as AuthenticatorVerifyRouteImport } from './routes/authenticator-verify'
import { Route as AuthenticatorQrRouteImport } from './routes/authenticator-qr'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminResourcesRouteImport } from './routes/admin.resources'
import { Route as AdminPlatformRouteImport } from './routes/admin.platform'
import { Route as AdminPatientsRouteImport } from './routes/admin.patients'
import { Route as AdminFormsRouteImport } from './routes/admin.forms'
import { Route as AdminDashboardsRouteImport } from './routes/admin.dashboards'
import { Route as AdminCliniciansRouteImport } from './routes/admin.clinicians'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminPatientsNewRouteImport } from './routes/admin.patients.new'
import { Route as AdminPatientsIdRouteImport } from './routes/admin.patients.$id'
import { Route as AdminPatientsNewSupportersRouteImport } from './routes/admin.patients.new.supporters'
import { Route as AdminPatientsNewReviewRouteImport } from './routes/admin.patients.new.review'
import { Route as AdminPatientsNewDoneRouteImport } from './routes/admin.patients.new.done'

const VerifyMethodRoute = VerifyMethodRouteImport.update({
  id: '/verify-method',
  path: '/verify-method',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsVerifyRoute = SmsVerifyRouteImport.update({
  id: '/sms-verify',
  path: '/sms-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsPhoneRoute = SmsPhoneRouteImport.update({
  id: '/sms-phone',
  path: '/sms-phone',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordRoute = PasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpiredRoute = ExpiredRouteImport.update({
  id: '/expired',
  path: '/expired',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteSkippedRoute = CompleteSkippedRouteImport.update({
  id: '/complete-skipped',
  path: '/complete-skipped',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatorVerifyRoute = AuthenticatorVerifyRouteImport.update({
  id: '/authenticator-verify',
  path: '/authenticator-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatorQrRoute = AuthenticatorQrRouteImport.update({
  id: '/authenticator-qr',
  path: '/authenticator-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourcesRoute = AdminResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlatformRoute = AdminPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormsRoute = AdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardsRoute = AdminDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCliniciansRoute = AdminCliniciansRouteImport.update({
  id: '/clinicians',
  path: '/clinicians',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsNewRoute = AdminPatientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPatientsRoute,
} as any)
const AdminPatientsIdRoute = AdminPatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPatientsRoute,
} as any)
const AdminPatientsNewSupportersRoute =
  AdminPatientsNewSupportersRouteImport.update({
    id: '/supporters',
    path: '/supporters',
    getParentRoute: () => AdminPatientsNewRoute,
  } as any)
const AdminPatientsNewReviewRoute = AdminPatientsNewReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AdminPatientsNewRoute,
} as any)
const AdminPatientsNewDoneRoute = AdminPatientsNewDoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => AdminPatientsNewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/authenticator-qr': typeof AuthenticatorQrRoute
  '/authenticator-verify': typeof AuthenticatorVerifyRoute
  '/complete': typeof CompleteRoute
  '/complete-skipped': typeof CompleteSkippedRoute
  '/expired': typeof ExpiredRoute
  '/password': typeof PasswordRoute
  '/sms-phone': typeof SmsPhoneRoute
  '/sms-verify': typeof SmsVerifyRoute
  '/verify-method': typeof VerifyMethodRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/clinicians': typeof AdminCliniciansRoute
  '/admin/dashboards': typeof AdminDashboardsRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/patients': typeof AdminPatientsRouteWithChildren
  '/admin/platform': typeof AdminPlatformRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/admin/patients/new': typeof AdminPatientsNewRouteWithChildren
  '/admin/patients/new/done': typeof AdminPatientsNewDoneRoute
  '/admin/patients/new/review': typeof AdminPatientsNewReviewRoute
  '/admin/patients/new/supporters': typeof AdminPatientsNewSupportersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authenticator-qr': typeof AuthenticatorQrRoute
  '/authenticator-verify': typeof AuthenticatorVerifyRoute
  '/complete': typeof CompleteRoute
  '/complete-skipped': typeof CompleteSkippedRoute
  '/expired': typeof ExpiredRoute
  '/password': typeof PasswordRoute
  '/sms-phone': typeof SmsPhoneRoute
  '/sms-verify': typeof SmsVerifyRoute
  '/verify-method': typeof VerifyMethodRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/clinicians': typeof AdminCliniciansRoute
  '/admin/dashboards': typeof AdminDashboardsRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/patients': typeof AdminPatientsRouteWithChildren
  '/admin/platform': typeof AdminPlatformRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin': typeof AdminIndexRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/admin/patients/new': typeof AdminPatientsNewRouteWithChildren
  '/admin/patients/new/done': typeof AdminPatientsNewDoneRoute
  '/admin/patients/new/review': typeof AdminPatientsNewReviewRoute
  '/admin/patients/new/supporters': typeof AdminPatientsNewSupportersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/authenticator-qr': typeof AuthenticatorQrRoute
  '/authenticator-verify': typeof AuthenticatorVerifyRoute
  '/complete': typeof CompleteRoute
  '/complete-skipped': typeof CompleteSkippedRoute
  '/expired': typeof ExpiredRoute
  '/password': typeof PasswordRoute
  '/sms-phone': typeof SmsPhoneRoute
  '/sms-verify': typeof SmsVerifyRoute
  '/verify-method': typeof VerifyMethodRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/clinicians': typeof AdminCliniciansRoute
  '/admin/dashboards': typeof AdminDashboardsRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/patients': typeof AdminPatientsRouteWithChildren
  '/admin/platform': typeof AdminPlatformRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/admin/patients/new': typeof AdminPatientsNewRouteWithChildren
  '/admin/patients/new/done': typeof AdminPatientsNewDoneRoute
  '/admin/patients/new/review': typeof AdminPatientsNewReviewRoute
  '/admin/patients/new/supporters': typeof AdminPatientsNewSupportersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/authenticator-qr'
    | '/authenticator-verify'
    | '/complete'
    | '/complete-skipped'
    | '/expired'
    | '/password'
    | '/sms-phone'
    | '/sms-verify'
    | '/verify-method'
    | '/admin/audit'
    | '/admin/clinicians'
    | '/admin/dashboards'
    | '/admin/forms'
    | '/admin/patients'
    | '/admin/platform'
    | '/admin/resources'
    | '/admin/'
    | '/admin/patients/$id'
    | '/admin/patients/new'
    | '/admin/patients/new/done'
    | '/admin/patients/new/review'
    | '/admin/patients/new/supporters'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authenticator-qr'
    | '/authenticator-verify'
    | '/complete'
    | '/complete-skipped'
    | '/expired'
    | '/password'
    | '/sms-phone'
    | '/sms-verify'
    | '/verify-method'
    | '/admin/audit'
    | '/admin/clinicians'
    | '/admin/dashboards'
    | '/admin/forms'
    | '/admin/patients'
    | '/admin/platform'
    | '/admin/resources'
    | '/admin'
    | '/admin/patients/$id'
    | '/admin/patients/new'
    | '/admin/patients/new/done'
    | '/admin/patients/new/review'
    | '/admin/patients/new/supporters'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/authenticator-qr'
    | '/authenticator-verify'
    | '/complete'
    | '/complete-skipped'
    | '/expired'
    | '/password'
    | '/sms-phone'
    | '/sms-verify'
    | '/verify-method'
    | '/admin/audit'
    | '/admin/clinicians'
    | '/admin/dashboards'
    | '/admin/forms'
    | '/admin/patients'
    | '/admin/platform'
    | '/admin/resources'
    | '/admin/'
    | '/admin/patients/$id'
    | '/admin/patients/new'
    | '/admin/patients/new/done'
    | '/admin/patients/new/review'
    | '/admin/patients/new/supporters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatorQrRoute: typeof AuthenticatorQrRoute
  AuthenticatorVerifyRoute: typeof AuthenticatorVerifyRoute
  CompleteRoute: typeof CompleteRoute
  CompleteSkippedRoute: typeof CompleteSkippedRoute
  ExpiredRoute: typeof ExpiredRoute
  PasswordRoute: typeof PasswordRoute
  SmsPhoneRoute: typeof SmsPhoneRoute
  SmsVerifyRoute: typeof SmsVerifyRoute
  VerifyMethodRoute: typeof VerifyMethodRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-method': {
      id: '/verify-method'
      path: '/verify-method'
      fullPath: '/verify-method'
      preLoaderRoute: typeof VerifyMethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms-verify': {
      id: '/sms-verify'
      path: '/sms-verify'
      fullPath: '/sms-verify'
      preLoaderRoute: typeof SmsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms-phone': {
      id: '/sms-phone'
      path: '/sms-phone'
      fullPath: '/sms-phone'
      preLoaderRoute: typeof SmsPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password': {
      id: '/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof PasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expired': {
      id: '/expired'
      path: '/expired'
      fullPath: '/expired'
      preLoaderRoute: typeof ExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-skipped': {
      id: '/complete-skipped'
      path: '/complete-skipped'
      fullPath: '/complete-skipped'
      preLoaderRoute: typeof CompleteSkippedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticator-verify': {
      id: '/authenticator-verify'
      path: '/authenticator-verify'
      fullPath: '/authenticator-verify'
      preLoaderRoute: typeof AuthenticatorVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticator-qr': {
      id: '/authenticator-qr'
      path: '/authenticator-qr'
      fullPath: '/authenticator-qr'
      preLoaderRoute: typeof AuthenticatorQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resources': {
      id: '/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AdminResourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/platform': {
      id: '/admin/platform'
      path: '/platform'
      fullPath: '/admin/platform'
      preLoaderRoute: typeof AdminPlatformRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forms': {
      id: '/admin/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboards': {
      id: '/admin/dashboards'
      path: '/dashboards'
      fullPath: '/admin/dashboards'
      preLoaderRoute: typeof AdminDashboardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clinicians': {
      id: '/admin/clinicians'
      path: '/clinicians'
      fullPath: '/admin/clinicians'
      preLoaderRoute: typeof AdminCliniciansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients/new': {
      id: '/admin/patients/new'
      path: '/new'
      fullPath: '/admin/patients/new'
      preLoaderRoute: typeof AdminPatientsNewRouteImport
      parentRoute: typeof AdminPatientsRoute
    }
    '/admin/patients/$id': {
      id: '/admin/patients/$id'
      path: '/$id'
      fullPath: '/admin/patients/$id'
      preLoaderRoute: typeof AdminPatientsIdRouteImport
      parentRoute: typeof AdminPatientsRoute
    }
    '/admin/patients/new/supporters': {
      id: '/admin/patients/new/supporters'
      path: '/supporters'
      fullPath: '/admin/patients/new/supporters'
      preLoaderRoute: typeof AdminPatientsNewSupportersRouteImport
      parentRoute: typeof AdminPatientsNewRoute
    }
    '/admin/patients/new/review': {
      id: '/admin/patients/new/review'
      path: '/review'
      fullPath: '/admin/patients/new/review'
      preLoaderRoute: typeof AdminPatientsNewReviewRouteImport
      parentRoute: typeof AdminPatientsNewRoute
    }
    '/admin/patients/new/done': {
      id: '/admin/patients/new/done'
      path: '/done'
      fullPath: '/admin/patients/new/done'
      preLoaderRoute: typeof AdminPatientsNewDoneRouteImport
      parentRoute: typeof AdminPatientsNewRoute
    }
  }
}

interface AdminPatientsNewRouteChildren {
  AdminPatientsNewDoneRoute: typeof AdminPatientsNewDoneRoute
  AdminPatientsNewReviewRoute: typeof AdminPatientsNewReviewRoute
  AdminPatientsNewSupportersRoute: typeof AdminPatientsNewSupportersRoute
}

const AdminPatientsNewRouteChildren: AdminPatientsNewRouteChildren = {
  AdminPatientsNewDoneRoute: AdminPatientsNewDoneRoute,
  AdminPatientsNewReviewRoute: AdminPatientsNewReviewRoute,
  AdminPatientsNewSupportersRoute: AdminPatientsNewSupportersRoute,
}

const AdminPatientsNewRouteWithChildren =
  AdminPatientsNewRoute._addFileChildren(AdminPatientsNewRouteChildren)

interface AdminPatientsRouteChildren {
  AdminPatientsIdRoute: typeof AdminPatientsIdRoute
  AdminPatientsNewRoute: typeof AdminPatientsNewRouteWithChildren
}

const AdminPatientsRouteChildren: AdminPatientsRouteChildren = {
  AdminPatientsIdRoute: AdminPatientsIdRoute,
  AdminPatientsNewRoute: AdminPatientsNewRouteWithChildren,
}

const AdminPatientsRouteWithChildren = AdminPatientsRoute._addFileChildren(
  AdminPatientsRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCliniciansRoute: typeof AdminCliniciansRoute
  AdminDashboardsRoute: typeof AdminDashboardsRoute
  AdminFormsRoute: typeof AdminFormsRoute
  AdminPatientsRoute: typeof AdminPatientsRouteWithChildren
  AdminPlatformRoute: typeof AdminPlatformRoute
  AdminResourcesRoute: typeof AdminResourcesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminCliniciansRoute: AdminCliniciansRoute,
  AdminDashboardsRoute: AdminDashboardsRoute,
  AdminFormsRoute: AdminFormsRoute,
  AdminPatientsRoute: AdminPatientsRouteWithChildren,
  AdminPlatformRoute: AdminPlatformRoute,
  AdminResourcesRoute: AdminResourcesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatorQrRoute: AuthenticatorQrRoute,
  AuthenticatorVerifyRoute: AuthenticatorVerifyRoute,
  CompleteRoute: CompleteRoute,
  CompleteSkippedRoute: CompleteSkippedRoute,
  ExpiredRoute: ExpiredRoute,
  PasswordRoute: PasswordRoute,
  SmsPhoneRoute: SmsPhoneRoute,
  SmsVerifyRoute: SmsVerifyRoute,
  VerifyMethodRoute: VerifyMethodRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
